### ISSUE TITLE
cmake报错

### ISSUE THREAD

**Issue by xiaomujiang** [anyongjin/pylsd2#1]
hi,  我在ubuntu18机器上，执行下面的命令，出现了报错
cd source && mkdir build_so && cd build_so
cmake ..
后报错
/source/build_so# cmake ..
CMake Error: The source directory "/source" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by anyongjin** [comment]
cmake的第一个参数".."必须是包含CMakeLists.txt的文件夹。
目录层级有变化，readme没及时更新导致的，pull下最新的readme看下吧，现在推好了
@xiaomujiang
